// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvl1QvtsbAASQuKQHqEOkIwWPAJaVBtLc',
    appId: '1:308030747704:web:2cfe8a695727272e8962cd',
    messagingSenderId: '308030747704',
    projectId: 'coffee-app-f2727',
    authDomain: 'coffee-app-f2727.firebaseapp.com',
    storageBucket: 'coffee-app-f2727.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMsTLaGZ4kE_MbfiU12k0C1JzEV7AN_pE',
    appId: '1:308030747704:android:988046fac59ecfa48962cd',
    messagingSenderId: '308030747704',
    projectId: 'coffee-app-f2727',
    storageBucket: 'coffee-app-f2727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDgoJPdns0pVO1kAdWkZja5pGAFTrIf8M',
    appId: '1:308030747704:ios:9c13149cff0619ce8962cd',
    messagingSenderId: '308030747704',
    projectId: 'coffee-app-f2727',
    storageBucket: 'coffee-app-f2727.appspot.com',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDgoJPdns0pVO1kAdWkZja5pGAFTrIf8M',
    appId: '1:308030747704:ios:3d86f5a121c1801f8962cd',
    messagingSenderId: '308030747704',
    projectId: 'coffee-app-f2727',
    storageBucket: 'coffee-app-f2727.appspot.com',
    iosBundleId: 'com.example.coffeeApp.RunnerTests',
  );
}
